/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "surface-container-highest": "#462f2c",
        "tertiary-container": "#0071d2",
        "surface-bright": "#4a3331",
        "secondary-container": "#921512",
        "outline-variant": "#5e3f3b",
        "on-secondary": "#690004",
        "error": "#ffb4ab",
        "surface-variant": "#462f2c",
        "primary-fixed-dim": "#ffb4aa",
        "on-primary-fixed-variant": "#930008",
        "on-primary-container": "#fff4f3",
        "primary-container": "#e30514",
        "inverse-surface": "#fedad6",
        "background": "#131313",
        "on-secondary-fixed-variant": "#8e1210",
        "on-secondary-container": "#ff9f93",
        "on-primary": "#690004",
        "on-background": "#fedad6",
        "inverse-on-surface": "#412b28",
        "on-secondary-fixed": "#410001",
        "on-tertiary-fixed": "#001c3b",
        "inverse-primary": "#c0000e",
        "outline": "#af8782",
        "surface-container": "#2e1a18",
        "secondary-fixed": "#ffdad5",
        "tertiary-fixed-dim": "#a7c8ff",
        "surface-container-lowest": "#1a0908",
        "on-error": "#690005",
        "on-primary-fixed": "#410001",
        "tertiary": "#a7c8ff",
        "secondary": "#ffb4aa",
        "on-tertiary": "#003060",
        "primary": "#ffb4aa",
        "surface-container-high": "#1c1b1b",
        "surface-container-low": "#1c1b1b",
        "on-tertiary-fixed-variant": "#004787",
        "surface-dim": "#131313",
        "secondary-fixed-dim": "#ffb4aa",
        "on-surface-variant": "#e9bcb6",
        "surface-tint": "#ffb4aa",
        "primary-fixed": "#ffdad5",
        "on-surface": "#e5e2e1",
        "on-error-container": "#ffdad6",
        "on-tertiary-container": "#f4f6ff",
        "tertiary-fixed": "#d5e3ff",
        "surface": "#131313",
        "error-container": "#93000a"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Inter"],
        "label": ["Lexend"]
      },
    },
  },
  plugins: [],
}
